USE [master]
GO

/****** Object:  Database [UdeS.Cefti.Inf735.Lab01.Ex1.DW]    Script Date: 10/31/2018 8:42:16 PM ******/
DROP DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW]
GO

/****** Object:  Database [UdeS.Cefti.Inf735.Lab01.Ex1.DW]    Script Date: 10/31/2018 8:42:16 PM ******/
CREATE DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UdeS.Cefti.Inf735.Lab01.Ex1.DW',
 FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UdeS.Cefti.Inf735.Lab01.Ex1.DW.mdf' ,
 SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UdeS.Cefti.Inf735.Lab01.Ex1.DW_log',
 FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UdeS.Cefti.Inf735.Lab01.Ex1.DW_log.ldf' ,
 SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] MODIFY FILEGROUP [PRIMARY] AUTOGROW_ALL_FILES
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UdeS.Cefti.Inf735.Lab01.Ex1.DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET ARITHABORT OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET RECOVERY FULL 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET  MULTI_USER 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UdeS.Cefti.Inf735.Lab01.Ex1.DW] SET  READ_WRITE 
GO

